apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    namespace: dev
    server: https://kubernetes.docker.internal:6443
  project: default
  source:
    path: dev
    repoURL: https://github.com/lnazure/argocdtest.git
    targetRevision: appsets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true